### ISSUE TITLE
Cannot run all samples

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-blazor-examples#211]
Following the steps described [here](https://github.com/IgniteUI/igniteui-blazor-examples#running-all-samples) when I am trying to restore the NuGet packages at this step:

- right click solution and select **Restore NuGet Packages** menu item

I get this errors:
- Unable to find package IgniteUI.Blazor with version (>= 21.2.29)
- Unable to find package IgniteUI.Blazor.Doxuments.Core with version (>= 21.2.29)
- Unable to find package IgniteUI.Blazor.Doxuments.Excel with version (>= 21.2.29)

**Comment by mddifilippo89** [comment]
The browser and all the samples were updated to .NET 6. VS 2019 will no longer work. You need to use VS 2022. I'll update the ReadMe to reflect this.

**Comment by the-black-wolf** [comment]
@mddifilippo89 it doesn't work in .net 6 /vs2022 either. The referenced IgniteUI.Blazor (21.2.29) is not published on Infragistics licensed packages source ("package not found" on https://packages.infragistics.com/nuget/licensed/Packages(Id='IgniteUI.Blazor',Version='21.2.29')) 

The latest version available is 21.2.22. You guys seem to have access to the unpublished version.

**Comment by mddifilippo89** [comment]
To be clear the you should be using 21.2.22 as that is what the master branch is targeting and the latest one available.

There are a couple of breaking changes that need fixing in DatePicker and Calendar

IgbDateRangeDescriptor[] > IgbDateRangeDescriptor

IgbSelectedItemChangedEventArgs > IgbValueChangedEventArgs

**Comment by the-black-wolf** [comment]
@mddifilippo89 ah ok its in the master branch which is not the default branch. weird flex though, making vnext the default branch, not really a conventional behavior. Maybe you should make a note of that in readme.

**Comment by IvayloG** [comment]
@mddifilippo89 What is the state of this issue? Currently, when using either 21.2.52 or  21.2.869-dev under vNext, the hosting fails with a failed build dialog with multiple errors in the browser's console.

Attaching VS snippet for details.
![image](https://user-images.githubusercontent.com/4296944/161714359-f654ab36-7e0d-4672-8e5a-d8ec747dd742.png)

**Comment by HUSSAR-mtrela** [comment]
@IvayloG please get latest on vnext branch because we are targeting 21.2.52 instead of 21.2.269-dev packages

![image](https://user-images.githubusercontent.com/11665978/161764420-8a242c70-25b2-42cc-a266-2da30e3f7fec.png)

**Comment by mddifilippo89** [comment]
@IvayloG Are you having any actual issues running the browser/samples? I don't run into any issues even with warnings.

**Comment by IvayloG** [comment]
No actually, no more.

**Comment by mddifilippo89** [comment]
These errors are actually causing the build to fail so I have to fix them. Thanks for the update.
