### ISSUE TITLE
Blazor Grid Pining Position Demo

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-blazor-examples#273]
~~Grid Pining position Demo is duplicated and both examples do not provide the option to change the pinning position~~

**EDIT: The DEMO is no longer duplicated, still I am not able to change the pinning position**

https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/column-pinning#demo

![image](https://user-images.githubusercontent.com/52001020/199428548-1aa10429-11c4-4d1b-8087-0b01ed888827.png)

**Comment by radomirchev** [comment]
The DEMO is no longer duplicated, still I am not able to change the pinning postion

**Comment by mddifilippo89** [comment]
NOT a bug. Its designed after the angular sample which is showcasing Right-Side pinning position at the ColumnPinningPosition.End
