### ISSUE TITLE
Input Blazor Component Example

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-blazor-examples#282]
First Example of the Input component says: "Input name", has input "User" and asks for "eg John Doe" 

When you enter what is asked for the input is RED because of:

<div class="container sample center">
    <h1>Greetings, @userName</h1>

![BUG Blazor Input Component](https://user-images.githubusercontent.com/52001020/198578335-ec7e3b23-33cc-4956-8702-a71344c9f393.gif)

**Comment by mddifilippo89** [comment]
@mtrela 
https://github.com/IgniteUI/igniteui-blazor-examples/pull/290

I removed the unnecessary displayType property.
