### ISSUE TITLE
Blazor Grid Binding Sample has too large font size 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#292]
grid-binding-nested-data-1 sample has too large font size:
https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/overview#complex-data-binding

in [column template](https://github.com/IgniteUI/igniteui-blazor-examples/blob/vnext/samples/grids/grid/binding-nested-data-1/wwwroot/events.js#L12) of the sample, replace h1 element with a DIV element and set bold font in the style.

![image](https://user-images.githubusercontent.com/11665978/202792123-dbf79d1e-c2f2-4765-a598-ec95ba304f98.png)

**Comment by agoldenbaum** [comment]
Fixed, but awaiting a build so I can verify
