### ISSUE TITLE
Blazor Grid Binding Sample has errors in DEV console

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#293]
[grid sample](https://staging.infragistics.com/blazor-client/samples/grids/grid-binding-nested-data-1)

Check if all data items have the data columns with the same names and there are no null values in data source

![image](https://user-images.githubusercontent.com/11665978/202792785-b1429b1e-468f-422b-8b76-9c81ae5d10c7.png)

**Comment by agoldenbaum** [comment]
Fixed. Awaiting a build so I can close this
