### ISSUE TITLE
Grid - Column Selection Mode cannot select mode

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-blazor-examples#309]
go to Grid - Column Selection Mode sample
at the top of the sample "Column Selection" is not a drop down and you cannot select the mode
![image](https://user-images.githubusercontent.com/18487709/223747174-0a9f32f6-6209-4dc2-bfcb-e4809440aad3.png)

**Comment by HUSSAR-mtrela** [comment]
@agoldenbaum  this issue might be already fixed in the latest

**Comment by HUSSAR-mtrela** [comment]
fixed on staging
https://staging.infragistics.com/blazor-client/samples/grids/grid/column-selection-mode
