### ISSUE TITLE
[Inputs / Date Time Input / Set Up Down] sample compilation error

### ISSUE THREAD

**Issue by turbobobbytraykov** [IgniteUI/igniteui-blazor-examples#312]
The following compilation errors for this sample are currently present in the **vnext** branch:

> \Pages\inputs\date-time-input\step-up-down\App.razor(63,45): Error CS0103: The name 'DatePart' does not exist in the current context
> \Pages\inputs\date-time-input\step-up-down\App.razor(67,47): Error CS0103: The name 'DatePart' does not exist in the current context

**Comment by HUSSAR-mtrela** [comment]
this API breaking change and it should be already fixed
