### ISSUE TITLE
Bullet-Graph sample throws errors in DEV console

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#330]
this issues was reported by @igDivya 
open sample
https://staging.infragistics.com/blazor-client/samples/gauges/bullet-graph/type-horizontal

errors occur in DEV console

@agoldenbaum try to reproduce this issue

![image](https://user-images.githubusercontent.com/11665978/230406877-512756eb-22c2-4a43-a969-fca564b74a37.png)

**Comment by agoldenbaum** [comment]
Marking this closed. I cannot reproduce the behavior as described
