### ISSUE TITLE
TreeGrid does not filter using specific filter condition 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#335]
this issues was reported by @igDivya
open sample
https://staging.infragistics.com/blazor-client/samples/grids/tree-grid/advanced-filtering-options 

@mddifilippo89 try to reproduce this issue

Check this advance filter condition 
![image](https://user-images.githubusercontent.com/11665978/230407647-704b9492-f770-422b-a8c3-9478533f8a2b.png)

Expected:
![image](https://user-images.githubusercontent.com/11665978/230407801-ea0595ca-ea22-4a84-82ce-c6b253a60866.png)

**Comment by agoldenbaum** [comment]
The expectation here is incorrect. The first screenshot is applying a filter of Age != 42. This means that all of the records with Age != 42 will be filtered **in**. In the sample, the only record that has Age = 42 has children, and so it is greyed out as the children still satisfy the filter and we show the child elements.
