### ISSUE TITLE
Grid Select the checkbox throw error in DEV console

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#336]
this issues was reported by @igDivya
open sample
https://staging.infragistics.com/blazor-client/samples/grids/tree-grid/row-selection-template-numbers

@mddifilippo89 try to reproduce this issue

![image](https://user-images.githubusercontent.com/11665978/230409261-2610b6a9-116d-4d1d-8743-3e93a776eb48.png)

**Comment by agoldenbaum** [comment]
I cannot seem to reproduce the behavior depicted in the screenshot. Marking closed
