### ISSUE TITLE
Grid throws errors when clicking on Pin columns

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#338]
this issues was reported by @igDivya

open either WC or Blazor sample:
https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/column-moving-options
https://staging.infragistics.com/blazor-client/samples/grids/grid/column-moving-options

click on the Pin columns
Grid throws errors in DEV console

@mddifilippo89 check if this is an issue in sample or product

![image](https://user-images.githubusercontent.com/11665978/230413216-db221bb7-aa75-46ae-bfa3-3f687fa907b4.png)

**Comment by agoldenbaum** [comment]
Marking this closed as it is a bug in the product, but this issue is a duplicate to this one: https://github.com/IgniteUI/igniteui-blazor-examples/issues/308. Bug linked in the other issue.
