### ISSUE TITLE
Grid throws error when clicking checkbox 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#339]
this issues was reported by @igDivya

open either WC or Blazor sample:
https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/conditional-row-selectors
https://staging.infragistics.com/blazor-client/samples/grids/grid/conditional-row-selectors
click any checkbox 
Grid throws errors

@mddifilippo89 check if this is an issue in sample or product

![image](https://user-images.githubusercontent.com/11665978/230415445-8c13d9d0-8eaa-4ad2-8595-5fff96dd179c.png)

![image](https://user-images.githubusercontent.com/11665978/230415528-d0f1bc78-5bb7-40be-891a-21f608569099.png)

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-webcomponents/issues/740

**Comment by mddifilippo89** [comment]
no longer seeing this issue.
