### ISSUE TITLE
Grid - Multiple Samples throw errors in DEV console

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#340]
this issues was reported by @igDivya

open
https://staging.infragistics.com/blazor-client/samples/grids/grid/clipboard-operations
https://staging.infragistics.com/blazor-client/samples/grids/grid/row-selection-template-numbers

grid throw errors in DEV console

@mddifilippo89 check if this is an issue in sample or product

NOTE that these errors do not occur in WC samples.
https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/clipboard-operations
https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/row-selection-template-numbers

![image](https://user-images.githubusercontent.com/11665978/230415891-6d432b59-d6c0-47d0-84cb-baa4edf8a1e2.png)

**Comment by mddifilippo89** [comment]
Redundant
https://github.com/IgniteUI/igniteui-blazor-examples/issues/341
