### ISSUE TITLE
TreeGrid sample throws an error in DEV console

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#341]
this issues was reported by @igDivya

https://staging.infragistics.com/blazor-client/samples/grids/tree-grid/clipboard-operations 
TreeGrid sample throws an error in DEV console

@mddifilippo89 check if this is an issue in sample or product

![image](https://user-images.githubusercontent.com/11665978/230417909-9ba04d0b-0851-4a97-8c3f-7891f2c68dae.png)

**Comment by mddifilippo89** [comment]
no longer an issue
