### ISSUE TITLE
tree-grid editing-columns sample throws error

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#423]
the [tree-grid editing-columns](https://staging.infragistics.com/blazor-client/samples/grids/tree-grid/editing-columns) sample throws error in DEV tools console:
`tree-grid-editing-columns.js:2 Uncaught SyntaxError: Cannot use import statement outside a module`

because this [event template](https://infragistics.visualstudio.com/NetAdvantage/_git/code-generation-library?path=/WebTreeGridCustomNumberSummary/Blazor.js&version=GB2023.1&line=2&lineEnd=3&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) is importing WC class. Graham said that this is incorrect way of accessing this class and he will provide a solution in the next release. Meanwhile, we will exclude the /grids/tree-grid/editing-columns sample

**Comment by gmurray81** [comment]
not, next release, but rather probably shortly after the VR. Might even technically make it into the VR, but can't know for sure yet. Depends on if we generate a new build or not.

**Comment by RivaIvanova** [comment]
The `editing-columns.json` sample is modified to not include the `WebTreeGridCustomNumberSummary` summary template in order for the sample to be exported and properly visible for all the platforms.
https://github.com/IgniteUI/igniteui-xplat-examples/pull/638
https://github.com/IgniteUI/igniteui-blazor-examples/pull/745
