### ISSUE TITLE
DataChart sample is missing values for most of data points

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#553]
https://www.infragistics.com/blazor-client/samples/charts/data-chart/axis-stacking

![image](https://github.com/IgniteUI/igniteui-blazor-examples/assets/11665978/db207b3e-0912-455d-8436-048039aa3855)

**Comment by agoldenbaum** [comment]
Marking this as status: can't reproduce. I ran this sample isolated and ran the browser itself and all of the data points have the values that they should. This also matches what is on staging. Perhaps the browser needs a push to production?

![CantRepro](https://github.com/IgniteUI/igniteui-blazor-examples/assets/18269063/b6b29fa2-ed3d-486d-ae19-f42d82ee91fd)

**Comment by HUSSAR-mtrela** [comment]
I confirmed that this issue does not occur anymore
