### ISSUE TITLE
Single select combo and select does not allow selection.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-blazor-examples#644]
Go to: https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/combo/single-selection#blazor-single-selectoin-example
Or: https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/select#blazor-select-example
Open the combo/select and try to select a value.
Value does not show in the editor.

**Comment by mddifilippo89** [comment]
@MayaKirova @skrustev @damyanpetev 
This is a critical issue 
https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/30366

**Comment by MayaKirova** [comment]
@mddifilippo89 Fixed, merged and staging is updated.
