### ISSUE TITLE
Multi Column Combobox shows empty column

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-blazor-examples#77]
@mddifilippo89 can your remove or replace the ID column in this sample because this column is empty

![image](https://user-images.githubusercontent.com/11665978/101049665-b9289600-3551-11eb-9fda-fe0f2bdad646.png)

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-blazor-examples/pull/78
