### ISSUE TITLE
[PivotGrid] Data Selector sample: Filtering does not work

### ISSUE THREAD

**Issue by MarielaTihova** [IgniteUI/igniteui-blazor-examples#832]
Have a look at this Blazor sample: https://www.infragistics.com/blazor-client/grids/pivot-grid/data-selector

- From the "All Periods" deselect something, for example deselect 2018.
- Expected result: Grid should show data for the rest of the periods- 2019 & 2020
- Actual result: Grid shows NO DATA

Records in filter dialog:
![image](https://github.com/user-attachments/assets/1441985c-5a8a-4ef2-9840-0304a6d40ce4)

Show records in grid:
![image](https://github.com/user-attachments/assets/fc41078a-b49f-40ed-a80d-4c330d51e6ca)

**Comment by skrustev** [comment]
I've logged a separate issue, since this is somewhat a limitation to all platforms otherwise:
https://github.com/IgniteUI/igniteui-angular/issues/14990
