### ISSUE TITLE
[PivotGrid] Data Selector sample: Search does not work

### ISSUE THREAD

**Issue by MarielaTihova** [IgniteUI/igniteui-blazor-examples#833]
Have a look at this Blazor sample: https://www.infragistics.com/blazor-client/grids/pivot-grid/data-selector

- The search bar in the upper right corner is not working. 
- Expected result: It should work as in this WC Example: https://www.infragistics.com/webcomponents-demos/grids/pivot-grid/data-selector
- Actual result: It shows nothing

**Comment by skrustev** [comment]
This is already a known issue, but I've applied a workaround in the sample that is not too far of from how it should work for Blazor.
